#!/bin/bash

clear

echo -e "\033[4;36m © TwoSSH | 2018 All rights reserved \033[0m"

echo ""

echo -e "\033[1;36mStart PythonSocks\033[0m"
echo ""
echo -e "\033[1;31mVerificando... \033[0m"

sleep 2

abobora=/bin/
rosa=proxy80.py

if [ -e "$abobora$rosa" ] ; then
echo -e "\033[1;32mPort 80 OK √ \033[0m"
history -c
else
echo -e "\033[1;31mBaixando arquivos para porta 80...\033[0m"
wget https://raw.githubusercontent.com/twossh/TwoSSH/master/scripts/proxy80.py -O /bin/proxy80.py> /dev/null 2> /dev/null
history -c
fi

sleep 2

echo ""

echo -e "\033[1;31mRESPONDA ALGUMAS PERGUNTAS \033[0m"
echo ""

echo -e "\033[1;32mAbrir porta 80? \033[0m"
read -p "[s/n]: " -e -i s port80

service squid3 stop > /dev/null 2> /dev/null
service squid stop > /dev/null 2> /dev/null

if [[ "$port80" = 's' ]]; then
chmod a+x /bin/proxy80.py && screen -dmS screen python /bin/proxy80.py > /bin/proxy80.txt &
fi

echo ""
echo -e "\033[1;32mTudo pronto! \n\nTwoSSH \033[0m"
